ci:
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/frostming/fix-future-annotations
    rev: 0.5.0
    hooks:
      - id: fix-future-annotations

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        exclude: ^docs/
        additional_dependencies:
          - types-pygments
          - types-python-slugify
