ci:
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/frostming/fix-future-annotations
    rev: 0.2.0
    hooks:
      - id: fix-future-annotations

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
