language: python
sudo: false
cache: pip
dist: trusty
env: TOXENV=py,codecov

install: pip install tox-travis
script: tox

jobs:
  include:
    - stage: lint
      python: 3.6
      env: TOXENV=lint
    - python: "3.7"
      stage: test
      dist: xenial
      sudo: required
    - python: "3.6"
    - python: "3.5"
    - python: "2.7"
    - stage: packaging
      python: 3.6
      env: TOXENV=packaging
