from typing import Iterable

from .block import Document
from .helpers import MarkoExtension as MarkoExtension
from .helpers import load_extension as load_extension
from .html_renderer import HTMLRenderer as HTMLRenderer
from .parser import Parser as Parser
from .renderer import Renderer as Renderer

__all__: list[str]

class SetupDone(Exception): ...

class Markdown:
    def __init__(
        self,
        parser: type[Parser] = ...,
        renderer: type[Renderer] = ...,
        extensions: Iterable[str | MarkoExtension] | None = None,
    ) -> None: ...
    def use(self, *extensions: str | MarkoExtension) -> None: ...
    def convert(self, text: str) -> str: ...
    def __call__(self, text: str) -> str: ...
    def parse(self, text: str) -> Document: ...
    def render(self, parsed: Document) -> str: ...

def convert(text: str) -> str: ...
def parse(text: str) -> Document: ...
def render(parsed: Document) -> str: ...
