from contextlib import contextmanager
from typing import Any, Generator

from . import block, inline
from .element import Element
from .renderer import Renderer

class MarkdownRenderer(Renderer):
    # Narrowed return types for str-returning renderer
    def render(self, element: Element) -> str: ...
    def render_children(self, element: Any) -> str: ...

    def __init__(self) -> None: ...
    def __enter__(self) -> MarkdownRenderer: ...
    @contextmanager
    def container(
        self, prefix: str, second_prefix: str = ""
    ) -> Generator[None, None, None]: ...
    def render_paragraph(self, element: block.Paragraph) -> str: ...
    def render_list(self, element: block.List) -> str: ...
    def render_list_item(self, element: block.ListItem) -> str: ...
    def render_quote(self, element: block.Quote) -> str: ...
    def render_fenced_code(self, element: block.FencedCode) -> str: ...
    def render_code_block(self, element: block.CodeBlock) -> str: ...
    def render_html_block(self, element: block.HTMLBlock) -> str: ...
    def render_thematic_break(self, element: block.ThematicBreak) -> str: ...
    def render_heading(self, element: block.Heading) -> str: ...
    def render_setext_heading(self, element: block.SetextHeading) -> str: ...
    def render_blank_line(self, element: block.BlankLine) -> str: ...
    def render_link_ref_def(self, element: block.LinkRefDef) -> str: ...
    def render_emphasis(self, element: inline.Emphasis) -> str: ...
    def render_strong_emphasis(self, element: inline.StrongEmphasis) -> str: ...
    def render_inline_html(self, element: inline.InlineHTML) -> str: ...
    def render_link(self, element: inline.Link) -> str: ...
    def render_auto_link(self, element: inline.AutoLink) -> str: ...
    def render_image(self, element: inline.Image) -> str: ...
    def render_literal(self, element: inline.Literal) -> str: ...
    def render_raw_text(self, element: inline.RawText) -> str: ...
    def render_line_break(self, element: inline.LineBreak) -> str: ...
    def render_code_span(self, element: inline.CodeSpan) -> str: ...
