from . import block, element, inline, inline_parser
from .source import Source

BlockElementType = type[block.BlockElement]
InlineElementType = type[inline.InlineElement]
ElementType = BlockElementType | InlineElementType

class Parser:
    block_elements: dict[str, BlockElementType]
    inline_elements: dict[str, InlineElementType]
    def __init__(self) -> None: ...
    def add_element(self, element: ElementType) -> None: ...
    def parse(self, text: str) -> block.Document: ...
    def parse_source(self, source: Source) -> list[block.BlockElement]: ...
    def parse_inline(self, element: block.BlockElement, source: Source) -> None: ...
