from typing import Any, Callable, TypeVar

from .block import Document
from .element import Element

_T = TypeVar("_T", bound="Renderer")
_F = TypeVar("_F", bound=Callable[..., Any])

class Renderer:
    delegate: bool
    root_node: Document | None
    def __init__(self) -> None: ...
    def __enter__(self: _T) -> _T: ...
    def __exit__(self, *args: Any) -> None: ...
    def render(self, element: Element) -> Any: ...
    def render_children(self, element: Any) -> Any: ...

def force_delegate(func: _F) -> _F: ...
