import functools
import types
from contextlib import contextmanager
from typing import Generator, Literal, Match, Pattern, overload

from .block import BlockElement, Document
from .parser import Parser

class Source:
    parser: Parser
    pos: int
    match: Match[str] | None
    context: types.SimpleNamespace
    def __init__(self, text: str) -> None: ...
    @property
    def state(self) -> BlockElement: ...
    @property
    def root(self) -> Document: ...
    def push_state(self, element: BlockElement) -> None: ...
    def pop_state(self) -> BlockElement: ...
    @contextmanager
    def under_state(self, element: BlockElement) -> Generator[Source, None, None]: ...
    @property
    def exhausted(self) -> bool: ...
    @property
    def prefix(self) -> str: ...
    @staticmethod
    @functools.lru_cache
    def match_prefix(prefix: str, line: str) -> int: ...
    def expect_re(self, regexp: Pattern[str] | str) -> Match[str] | None: ...
    @overload
    def next_line(self, require_prefix: Literal[False] = ...) -> str: ...
    @overload
    def next_line(self, require_prefix: Literal[True] = ...) -> str | None: ...
    def consume(self) -> None: ...
    def anchor(self) -> None: ...
    def reset(self) -> None: ...
